### ISSUE TITLE
Validation Component - component.set throwing an error

### ISSUE THREAD

**Issue by mcarneiro** [jails-org/Components#2]
There's a undefined variable `cp` being called in this line. I think it should be `component`:

https://github.com/jails-org/Components/blob/v2/validation/validation.js#L27

```
component.set = function( fn ){
  fn.call( cp, instance );
};
```

This is generating an error:

```
Uncaught ReferenceError: cp is not defined
```

It seems to be a typo.

**Comment by mcarneiro** [comment]
Forgot to say that this is happening on branch `v2`.

**Comment by Javiani** [comment]
Ok, thanks @mcarneiro . It's fixed 👍
